Repository Malloc72P/todo-list, pull requests merged in 2021-04, with the labels that each got.

#15 프로젝트 리드미 작성했어요!
  README.md
Labels: all

#50 [FE] TodoLog 부분
  fe/todo-list/src/components/card/actionCard.jsx
  fe/todo-list/src/components/card/actionCardList.jsx
  fe/todo-list/src/components/header.jsx
  fe/todo-list/src/components/taskCardList.jsx
Labels: fe

#55 Time log 부분 시간 계산하는 로직 살짝 수정
  fe/todo-list/src/components/card/actionCard.jsx
  fe/todo-list/src/components/card/actionCardList.jsx
Labels: fe

#54 Raccoon 기능을 합치기 위한 pr
  fe/todo-list/src/components/card/card.jsx
  fe/todo-list/src/components/card/taskCardList.jsx
  fe/todo-list/src/components/column/column.jsx
  fe/todo-list/src/components/const.js
  fe/todo-list/src/components/view/body.jsx
Labels: fe

#56 card.jsx에 있던 컴포넌트들을 별도 파일로 분리
  fe/todo-list/src/components/card/actionCard.jsx
  fe/todo-list/src/components/card/activeTask.jsx
  fe/todo-list/src/components/card/cancelPopup.jsx
  fe/todo-list/src/components/card/caption.jsx
  fe/todo-list/src/components/card/card.jsx
  fe/todo-list/src/components/card/defaultTask.jsx
  fe/todo-list/src/components/card/form.jsx
  fe/todo-list/src/components/card/taskContents.jsx
  fe/todo-list/src/components/card/taskTitle.jsx
Labels: fe

#58 [Raccoon] 현재까지의 작업입니다.
  fe/todo-list/src/components/card/actionCardList.jsx
  fe/todo-list/src/components/card/activeTask.jsx
  fe/todo-list/src/components/card/cancelPopup.jsx
  fe/todo-list/src/components/card/card.jsx
  fe/todo-list/src/components/card/defaultTask.jsx
  fe/todo-list/src/components/card/form.jsx
  fe/todo-list/src/components/card/taskCardCount.jsx
  fe/todo-list/src/components/card/taskCardList.jsx
  fe/todo-list/src/components/column/column.jsx
  fe/todo-list/src/components/column/columnHeader.jsx
  fe/todo-list/src/components/column/columnList.jsx
  fe/todo-list/src/components/const.js
  fe/todo-list/src/components/deleteData.js
  fe/todo-list/src/components/icon/icon.jsx
  fe/todo-list/src/components/popup/cancelPopup.jsx
  fe/todo-list/src/components/popup/popup.jsx
  fe/todo-list/src/components/postData.js
  fe/todo-list/src/components/util.js
  fe/todo-list/src/components/view/body.jsx
  fe/todo-list/src/components/view/header.jsx
  fe/todo-list/src/const.js
  fe/todo-list/src/index.css
Labels: fe

#59 Team 12 back jdbc
  README.md
  be/README.md
  be/todo/build.gradle
  be/todo/src/main/java/com/codesquad/todo/web/config/MyCommandLineRunner.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/ColumnController.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/ExceptionController.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/TaskController.java
  be/todo/src/main/java/com/codesquad/todo/web/controller/TodoLogController.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/Column.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/ColumnRepository.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/Task.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TaskRepository.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoColumn.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoLog.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoLogActionCommand.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoLogRepository.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoTask.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/TodoUser.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/User.java
  be/todo/src/main/java/com/codesquad/todo/web/domain/UserRepository.java
  be/todo/src/main/java/com/codesquad/todo/web/exceptions/ColumnNotFoundException.java
  be/todo/src/main/java/com/codesquad/todo/web/exceptions/IllegalActionCommandException.java
  be/todo/src/main/java/com/codesquad/todo/web/exceptions/InvalidEntityDetectedException.java
  be/todo/src/main/java/com/codesquad/todo/web/exceptions/TaskNotFoundException.java
  be/todo/src/main/java/com/codesquad/todo/web/exceptions/UserNotFoundException.java
  be/todo/src/main/java/com/codesquad/todo/web/service/TodoColumnService.java
  be/todo/src/main/java/com/codesquad/todo/web/service/TodoLogService.java
  be/todo/src/main/java/com/codesquad/todo/web/service/TodoTaskService.java
  be/todo/src/main/java/com/codesquad/todo/web/service/TodoUserService.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/ColumnDto.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/TaskDto.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/TaskParameterDto.java
  be/todo/src/main/java/com/codesquad/todo/web/service/dto/TodoLogDto.java
  be/todo/src/main/java/com/codesquad/todo/web/util/VerifyUtil.java
  be/todo/src/main/resources/application.properties
  be/todo/src/main/resources/schema.sql
  be/todo/src/test/java/com/codesquad/todo/web/domain/TodoUserRepositoryTest.java
  fe/todo-list/.gitignore
  fe/todo-list/README.md
  fe/todo-list/package-lock.json
  fe/todo-list/package.json
  fe/todo-list/public/index.html
  fe/todo-list/src/app.css
  fe/todo-list/src/app.jsx
  fe/todo-list/src/components/button/button.jsx
  fe/todo-list/src/components/card/card.jsx
  fe/todo-list/src/components/columnHeader/columnHeader.jsx
  fe/todo-list/src/components/icon/icon.jsx
  fe/todo-list/src/components/taskCardCount/taskCardCount.jsx
  fe/todo-list/src/index.css
  fe/todo-list/src/index.js
  fe/todo-list/yarn.lock
Labels: be

#61 [Raccoon] put요청 기능 추가
  fe/todo-list/src/components/card/actionCardList.jsx
  fe/todo-list/src/components/card/defaultTask.jsx
  fe/todo-list/src/components/const.js
  fe/todo-list/src/components/postData.js
  fe/todo-list/src/components/putData.js
  fe/todo-list/src/components/util.js
  fe/todo-list/src/components/view/header.jsx
Labels: fe
